@startuml
title reserver cours

actor ":Eleve" as Eleve
participant ":Reservations" as Reservations
participant ":Auto_ecole" as Auto_ecole

Eleve->Auto_ecole: accederPageReservationCours()

Eleve->Auto_ecole: selectionnerCours(idCours)

Auto_ecole->Reservations: reserverCours(idEleve, idCours)

Reservations->Reservations: verifierDisponibiliteCours(idCours)

alt
    Reservations->Auto_ecole: reservationCoursReussie(reservation)
    Auto_ecole->Eleve: reservationReussie(reservation)
else
    Reservations->Auto_ecole: reservationCoursEchouee(motif)
    Auto_ecole->Eleve: reservationEchouee(motif)
end
@enduml