@startuml
title reserver cours

actor ":Eleve" as Eleve
participant ":Reservations" as Reservations
participant ":Auto_ecole" as Auto_ecole

Eleve->AutoEcole: accederPageReservationCours()

Eleve->AutoEcole: selectionnerCours(idCours)

AutoEcole->Reservations: reserverCours(idEleve, idCours)

Reservations->Reservations: verifierDisponibiliteCours(idCours)

alt
    Reservations->AutoEcole: reservationCoursReussie(reservation)
    AutoEcole->Eleve: reservationReussie(reservation)
else
    Reservations->AutoEcole: reservationCoursEchouee(motif)
    AutoEcole->Eleve: reservationEchouee(motif)
end
@enduml