@startuml
participant Eleve
participant AutoEcole
participant Reservations

Eleve->AutoEcole: accederPageReservationCours()

Eleve->AutoEcole: selectionnerCours(idCours)

AutoEcole->Reservations: reserverCours(idEleve, idCours)

Reservations->Reservations: verifierDisponibiliteCours(idCours)

alt
    Reservations->AutoEcole: reservationCoursReussie(reservation)
    AutoEcole->Eleve: reservationReussie(reservation)
else
    Reservations->AutoEcole: reservationCoursEchouee(motif)
    AutoEcole->Eleve: reservationEchouee(motif)
end
@enduml