@startuml
participant Eleve
participant AutoEcole
participant ConnexionDemande

Eleve->AutoEcole: accederPageConnexion()

Eleve->AutoEcole: saisirIdentifiantMotDePasse(identifiant, motDePasse)

AutoEcole->ConnexionDemande: authentifierEleve(identifiant, motDePasse)

ConnexionDemande->Eleve: verifierIdentifiantMotDePasseEleve(identifiant, motDePasse)

alt
    ConnexionDemande->AutoEcole: authentificationEleveReussie(eleve)
    AutoEcole->Eleve: authentificationReussie(eleve)
else
    ConnexionDemande->AutoEcole: authentificationEleveEchouee()
    AutoEcole->Eleve: authentificationEchouee()
end
@enduml